name: 'Lake Test Args'
description: 'Run `lean-action` with `test-args` input and verify args are passed through'
inputs:
  toolchain:
    description: 'Toolchain to use for the test'
    required: true
runs:
  using: 'composite'
  steps:
    # TODO: once `lean-action` supports just setup, use it here
    - name: install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain ${{ inputs.toolchain }}
        echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: create lake package
      run: |
        lake init buildargs .lean
        lake update
      shell: bash

    - name: create test that verifies TEST_ARGS is set
      run: |
        {
          echo "@[test_runner]"
          echo "script dummy_test do"
          echo "  let testArgs <- IO.getEnv \"TEST_ARGS\""
          echo "  let value := testArgs.get!"
          echo "  IO.FS.writeFile \"test_args_output.txt\" value"
          echo "  return 0"
        } >> lakefile.lean
      shell: bash

    - name: "run `lean-action` with test-args"
      id: lean-action
      uses: ./
      with:
        test: true
        test-args: "--wfail"
        use-github-cache: false

    - name: verify `lean-action` outcome success
      env:
        OUTPUT_NAME: "lean-action.outcome"
        EXPECTED_VALUE: "success"
        ACTUAL_VALUE: ${{ steps.lean-action.outcome }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: verify test-args output
      env:
        OUTPUT_NAME: "test-args-output"
        EXPECTED_VALUE: "--wfail"
      run: |
        ACTUAL_VALUE=$(cat test_args_output.txt)
        export ACTUAL_VALUE
        .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: lake clean
      run: lake clean
      shell: bash

    - name: "run `lean-action` with multiple test args"
      id: lean-action-multiple-test-args
      uses: ./
      with:
        test: true
        test-args: "--log-level=warning --fail-level=warning"
        use-github-cache: false

    - name: verify `lean-action-multiple-test-args` outcome success
      env:
        OUTPUT_NAME: "lean-action-multiple-test-args.outcome"
        EXPECTED_VALUE: "success"
        ACTUAL_VALUE: ${{ steps.lean-action-multiple-test-args.outcome }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: verify multiple test-args output
      env:
        OUTPUT_NAME: "test-args-output"
        EXPECTED_VALUE: "--log-level=warning --fail-level=warning"
      run: |
        ACTUAL_VALUE=$(cat test_args_output.txt)
        export ACTUAL_VALUE
        .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash
