name: 'Lake Lint Success'
description: 'Run `lean-action` with `lake lint` and a successful dummy lint_driver'
inputs:
  toolchain:
    description: 'Toolchain to use for the test'
    required: true
runs: 
  using: 'composite'
  steps:
    # TODO: once `lean-action` supports just setup, use it here
    - name: install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain ${{ inputs.toolchain }}
        echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: create lake package
      run: |
        lake init dummylint .lean
        lake update
      shell: bash

    - name: create successful dummy lint
      run: |
        {
          echo "@[lint_driver]"
          echo "script dummy_lint do"
          echo "  println! \"Running fake lints...\""
          echo "  println! \"Fake lints passed!\""
          echo "  return 0" 
        } >> lakefile.lean
      shell: bash

    - name: "run `lean-action` with `lake lint`" 
      id: lean-action
      uses: ./
      with:
        lint: true
        use-github-cache: false
    
    - name: verify `lean-action` outcome success
      env:
        OUTPUT_NAME: "lean-action.outcome"
        EXPECTED_VALUE: "success"
        ACTUAL_VALUE: ${{ steps.lean-action.outcome }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: verify `lake lint` success
      env:
        OUTPUT_NAME: "lint-status"
        EXPECTED_VALUE: "SUCCESS"
        ACTUAL_VALUE: ${{ steps.lean-action.outputs.lint-status }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash
