name: 'Lake Check Test Failure'
description: |
  Run `lean-action` with `test: true` without a test_driver in the Lake workspace.
  Verify `lean-action` fails and `lake build` and `lake test` are not run.
inputs:
  toolchain:
    description: 'Toolchain to use for the test'
    required: true
runs: 
  using: 'composite'
  steps:
    # TODO: once `lean-action` supports just setup, use it here
    - name: install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain ${{ inputs.toolchain }}
        echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: create lake package
      run: |
        lake init dummytest
      shell: bash

    - name: "run `lean-action` with `test: true`" 
      id: lean-action
      uses: ./
      continue-on-error: true # required so that the action failure does not fail the workflow
      with:
        test: true
        use-github-cache: false
    
    - name: verify `lean-action` outcome failure
      env:
        OUTPUT_NAME: "lean-action.outcome"
        EXPECTED_VALUE: "failure"
        ACTUAL_VALUE: ${{ steps.lean-action.outcome }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: verify `lake build` not run
      env:
        OUTPUT_NAME: "build-status"
        EXPECTED_VALUE: "NOT_RUN"
        ACTUAL_VALUE: ${{ steps.lean-action.outputs.build-status }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash

    - name: verify `lake test` not run
      env:
        OUTPUT_NAME: "test-status"
        EXPECTED_VALUE: "NOT_RUN"
        ACTUAL_VALUE: ${{ steps.lean-action.outputs.test-status }}
      run: .github/functional_tests/test_helpers/verify_action_output.sh
      shell: bash
